collision_clearance: 0.10
debug_collisions: false

num_feature_basis_functions: 1
trajectory_duration: 6.0
num_time_steps: 50

collision_space:
  size_x: 3.0
  size_y: 3.0
  size_z: 4.0
  origin_x: 0.0
  origin_y: 0.0
  origin_z: 0.0
  resolution: 0.02
  collision_tolerance: 0.0
  max_propagation_distance: 0.25

max_rollouts: 20
min_rollouts: 20
num_rollouts_per_iteration: 16
use_noise_adaptation: true
noise_stddev: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
#noise_stddev: [4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0]
noise_min_stddev: [0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3]
#noise_stddev: [2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0]
#noise_stddev: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
noise_decay: [0.999, 0.999, 0.999, 0.999, 0.999, 0.999, 0.999]
write_to_file: false
use_openmp: false

features: 
#  -
#    class: stomp_moveit_interface/ExactCollisionFeature
  -
    class: stomp_moveit_interface/CollisionFeature
    report_validity: true # report state validity based on distance field
    collision_clearance: 0.10
    debug_collisions: false
